server:
  port: 8083
spring:
  application:
    name: zhengcs-seata-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account
    username: test
    password: 123456
    filters: stat,slf4j
    maxActive: 5
    maxWait: 60000
    minIdle: 1
    initialSize: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

dubbo:
  application:
    name: zhengcs-seata-account
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: N/A
    check: false
  consumer:
    check: false
    timeout: 10000
